### ISSUE TITLE
Error after upgrade to 2023.5.1

### ISSUE THREAD

**Issue by petervk** [jrfernandes/ontario_energy_board#25]
I just updated to 2023.5.1 and I'm getting the error below.

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/ontario_energy_board/__init__.py:21
Integration: Ontario Energy Board (documentation, issues)
First occurred: 2:40:48 PM (1 occurrences)
Last logged: 2:40:48 PM

Error setting up entry Alectra Utilities Corporation for ontario_energy_board
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ontario_energy_board/__init__.py", line 21, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by DaftHonk** [comment]
Fixed by #24 and merged. Install release v.0.3.3

**Comment by jrfernandes** [comment]
What he said 👆
